config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'static_pages#home'
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'

  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
  end

   devise_scope :user do
    get "/signup" => "devise/registrations#new"
  end

  get 'add_challenge' => 'challenges#new'
  get 'challenges' => 'challenges#index'
  get '/challenges/:challenge_id/solutions/add_solution' => 'solutions#new'
  get 'users/:id' => 'users#show'
  get 'search' => 'challenges#search_index'
  get '/category_search/:id/:category' => 'challenges#search_category'
  post '/challenges/add_top_three' => 'challenges#add_top_three'
  get '/challenges/:challenge_id/edit' => 'challenges#edit'
  post '/challenges/voting_stage' => 'challenges#voting_stage'
  post '/solutions/top_flag' => 'solutions#top_flag'
  post '/challenges/participate_stage' => 'challenges#participate_stage'

  resources :challenges do
    resources :solutions
    member do
    get :following
  end 
  end

  resources :users
  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
    <div class="container">
      <div class="row">
       <div class="span12">
        <div id="footer">

           <ul class="footer">

            <li>&copy 2015 innovateAladdin</li>&nbsp;&nbsp;
           
           <ul>

        </div>
     </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<link href='https://fonts.googleapis.com/css?family=Merriweather|Shadows+Into+Light' rel='stylesheet' type='text/css'>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header" style="margin: 20px">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="padding-top: 0px"><h4 style="font-family: 'Merriweather', serif; margin-top: 0px; color: #29A329">innovate<span style="font-family: 'Shadows Into Light', cursive; font-size: 1.4em; color: #121254">Aladdin</span><br>
      <span style="font-family: 'Merriweather', serif; margin-top: 0px; color: #29A329">by BlackRock</span></h4></a>
    </div>

    <% if user_signed_in? %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav" style="padding-top: 15px">
        <li><a href="/add_challenge">Add Challenge<span class="sr-only">(current)</span></a></li>
        
        <% if current_user.acct_type == 'admin' %>
          <li><a href="/challenges">View Challenges</a></li>
        <% elsif current_user.acct_type == 'innovator' %> 
          <li><%= link_to "My Profile", "/users/#{current_user.id}" %></li>
          <li><a href="/challenges">Top Three Challenges</a></li>
          <% end %>
          
        <li id="header_search"><%= form_tag(challenges_path, :method => "get", id: "search-form", class: 'navbar-form navbar-left') do %>
              <%= text_field_tag :search, params[:search], placeholder: "Search My Challenges", class: 'form-control' %>
              <%= submit_tag "Search", class: 'btn btn-default' %>
              <% end %>
        </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/about">About</a></li>
        <li><a href="/contact">Contact</a></li>
        <% if user_signed_in? %>
        <li><a href="/logout">Logout</a></li>
        <% else %>
        <li><a href="/signup">Sign up</a></li>
        <li><a href="/login">Login</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link href='https://fonts.googleapis.com/css?family=Patrick+Hand' rel='stylesheet' type='text/css'>
  <title>Innovate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
<%= yield %>
	<%= render 'layouts/footer' %>

</body>
</html>